# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
pandoc_version: 2.1.1
sudo: false
cache: packages
script:
  - Rscript -e 'xfun::in_dir("dir1", bookdown::render_book("index.Rmd", "bookdown::gitbook"))'
  - Rscript -e 'xfun::in_dir("dir2", bookdown::render_book("index.Rmd", "bookdown::gitbook"))'
  - cp -vr dir1/dir1 docs
  - cp -vr dir2/dir2 docs
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN #set in travis-ci dashboard
  on:
    branch: master
  local_dir: docs