# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
pandoc_version: 2.1.1
sudo: false
cache: packages
script:
  - Rscript -e 'xfun::in_dir("dir1", bookdown::render_book("index.Rmd"))'
  - cp -vr dir1/dir1 docs
  - Rscript -e 'xfun::in_dir("dir2", bookdown::render_book("index.Rmd"))'
  - Rscript -e 'file.copy(from = "dir2/dir2", to = "docs", recursive = TRUE)'